### ISSUE TITLE
No ability to not save mistakes

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/voicebank-ios#26]
When recording I often made mistakes reading the text. However these mistakes along with the good data are all sent to the server.

There needs to be some way for the user to not submit data they know is bad

**Comment by andrenatal** [comment]
Please double check with @mbebenita since he told to not do so.

**Comment by andrenatal** [comment]
You can cancel the recording while speaking (dragging the button down) but not after you finish speaking and before the upload.

**Comment by kdavis-mozilla** [comment]
At least to me this was not obvious. I think maybe having some instructions or hints or... would help the users.

**Comment by andrenatal** [comment]
Fixed with #46
