### ISSUE TITLE
Wave of wave-view has an "off-by-one" pixel error

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/voicebank-ios#27]
The left and right waves of the wave view of the audio do not meet in the middle of the screen there is a joint visible to the user.

**Comment by mbebenita** [comment]
What phone do you have? I can only test this on my iPhone 5se.

**Comment by kdavis-mozilla** [comment]
iPhone 6

![img_0296](https://cloud.githubusercontent.com/assets/12054740/23673692/7f10c5fa-0373-11e7-9afe-b306612b30f5.PNG)

**Comment by mbebenita** [comment]
Okay, yah, that's definitely busted.
