### ISSUE TITLE
Dates and numbers in the text need to be normalized

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/voicebank-ios#28]
There are numbers, e.g. 1926, in the text to be read that are not normalized.

In other words how does one say 1926?

- Nineteen twenty six
- One thousand nine hundred twenty six
- One thousand nine hundred and twenty six
- Nineteen hundred twenty six
- One nine two six
- ...

The actual way this is said is context dependent. Is it a date? Is it a population? Is it a...

**Comment by mbebenita** [comment]
Can we avoid numbers all together for now? I can see the ambiguity, but reading sentences with normalized numbers is pretty difficult "One thousand nine hundred and twenty six" is hard to say and it almost always stumps me.

**Comment by kdavis-mozilla** [comment]
If we avoid numbers, then any STT engine trained from the corpus will likely not be able to understand numbers.
