### ISSUE TITLE
There is no idependent validation of data

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/voicebank-ios#30]
As a user I can submit junk. I can not read the correct sentence, not read anything, curse, push the record button only for a quick moment....

The system is not protected against such sources of bad data.

**Comment by andrenatal** [comment]
@kdavis-mozilla How do you suggest to do such validation in this specific app?

**Comment by kdavis-mozilla** [comment]
There lots of ways...

- Have users X,Y, and Z validate data from user A (Majority rule)
- Send the data to an iOS STT engine, throw out results that don't match the text
- ...

**Comment by mbebenita** [comment]
So, some of this can obviously be done on the server side. On the client side, we can go the iOS STT  route.

**Comment by kdavis-mozilla** [comment]
@mbebenita How do you want to do it server side? Most server side solutions that come to mind are expensive in terms of time and money.

However, for example, the "majority rule" solution

> Have users X,Y, and Z validate data from user A (Majority rule)

Is not expensive in terms of time or money.

**Comment by mbebenita** [comment]
As a first step, we'll try the iOS STT approach. Next we'll look at having users cross-validate their data, although I don't really have a good idea how to do this on the front end.

The Google STT service costs $0.006 / 15 seconds (a single request is round up to 15 second intervals). Doesn't seem that expensive to me (at least as a starting point) ~ $1.5 / hour.

**Comment by kdavis-mozilla** [comment]
@mbebenita There are several problems with relying on of Google STT:

- When training on the produced corpus, our minimum achievable WER will be that of the Google STT engine.
- In the small the costs are reasonable, but we don't have the budget to scale this to the target 10k hours.
- Using the Google STT engine, retaining the audio and text, and training models off the results violates the Google STT terms of service[[1](https://cloud.google.com/terms/service-terms#12-google-cloud-platform-machine-learning-group)].

**Comment by mikehenrty** [comment]
Those are good points Kelly. Maybe we could take a hybrid approach, where we run the utteracne through some power STT engine, if the source text and source audio match exactly we consider it validated. If it doesn't match exactly, we use manual validation (either through the app, mechanical turk, or some other solution).

**Comment by andrenatal** [comment]
I implemented a passing through iOS STT API, and am sending the results along the sentence to the server. Note there are some requisition limits per device, so if the user send too many phrases in sequence this limit can be hit quickly.
