### ISSUE TITLE
The app does not collect gender info

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/voicebank-ios#31]
Is the voice it collecting male or female?

**Comment by andrenatal** [comment]
Please double check with @mbebenita since he told to not do so.

**Comment by kdavis-mozilla** [comment]
We should do this. It will be critical in future when we have to tune the STT engine to different distributions of genders that do not reflect the distribution naturally occurring in the VoiceBank users.

**Comment by mbebenita** [comment]
I said that we want to let the users jump straight in, minimize friction, and start recording samples. Then maybe a few sentences better, ask for details like gender, accent, etc.

**Comment by kdavis-mozilla** [comment]
@mbebenita Seems reasonable to me. The only slight problem might be for people who contribute a few sentences, then stop before we get any info on them.
