### ISSUE TITLE
The app does not collect accent info

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/voicebank-ios#33]
Is the accent of the collected voice east coast, west coast, Baltimore (Hon), Jamaican....

**Comment by andrenatal** [comment]
Please double check with @mbebenita since he told to not do so.

**Comment by kdavis-mozilla** [comment]
We should do this. It will be critical in future when we have to tune the STT engine to different distributions of accents that do not reflect the distribution naturally occurring in the VoiceBank users.

**Comment by mbebenita** [comment]
I said that we want to let the users jump straight in, minimize friction, and start recording samples. Then maybe a few sentences better, ask for details like gender, accent, etc. I am not opposed to asking earlier, I just couldn't think of a good way to do it back when we were looking at the web app.

**Comment by kdavis-mozilla** [comment]
@mbebenita Seems reasonable to me. The only slight problem might be for people who contribute a few sentences, then stop before we get any info on them.
