### ISSUE TITLE
Sync fades and thinner X

### ISSUE THREAD

**Issue by andrenatal** [mozilla/voicebank-ios#39]
A couple of comments from @mbebenita :

    - When you release the finger and it's away from the button, the X fades out over the span of a second or so. This is inconsistent with how the X appears, which doesn't have an animation. I'd add a fade in animation to the X as well, and make both animations shorter.

    - The X looks too much like an X. Ideally, I was envisioning a very thin X cross.

**Comment by andrenatal** [comment]
@mbebenita Is this better for you?

![screenshot 2017-03-10 14 03 05](https://cloud.githubusercontent.com/assets/973388/23814926/62fa0510-059a-11e7-925a-910240eafb18.png)

**Comment by mbebenita** [comment]
Looks better, maybe a bit smaller.

**Comment by andrenatal** [comment]
And this? 

![screenshot 2017-03-10 14 25 30](https://cloud.githubusercontent.com/assets/973388/23815505/7ab6ded2-059d-11e7-823f-b6ac8b76995f.png)

**Comment by mbebenita** [comment]
Good enough.
