### ISSUE TITLE
UI adjustments

### ISSUE THREAD

**Issue by andrenatal** [mozilla/voicebank-ios#47]
- Adjust disclaimer textview to its text content
- Better graphics to display the progress count

**Comment by mikehenrty** [comment]
And it would be cool to have a nice animation when the counter reaches 0. Also we should reset it to 100 (or maybe 200) when that happens rather than going into negative numbers.

**Comment by mikehenrty** [comment]
> Also we should reset it to 100 (or maybe 200) when that happens rather than going into negative numbers.
@psubhashish file #54 to take a look at this.
