### ISSUE TITLE
Would be nice to be able to hear the sentence before uploading.

### ISSUE THREAD

**Issue by mikehenrty** [mozilla/voicebank-ios#49]
The cancel action is not super intuitive, so it would be nice to have the option to playback, re-record, or submit after recording a sample.

**Comment by psubhashish** [comment]
I agree. I mis-read a couple of sentences but could not figure out how to rerecord.

**Comment by andrenatal** [comment]
I wanted to hear @mbebenita about this since we had some discussing about this in the past.

**Comment by mbebenita** [comment]
I am not opposed to having a way to review samples. Does anyone have any ideas how to make cancelling more intuitive?

**Comment by andrenatal** [comment]
Probably when @mikehenrty  posted that the startup instructions weren't in place yet?

**Comment by mikehenrty** [comment]
I think the cancel is nice for power users, so I don't think we should remove it. But if we had a way to review (replay), re-record, and manually submit (ie. just like murmur), then that solves the cancel problem.
