### ISSUE TITLE
Bip when start to record

### ISSUE THREAD

**Issue by andrenatal** [mozilla/voicebank-ios#6]

**Comment by mbebenita** [comment]
#8 adds this but we need better sounds. We should also add some kind of indication that the message has been submitted.

**Comment by andrenatal** [comment]
Fixed by #8

**Comment by mbebenita** [comment]
This is not solved yet, as I commented above.

**Comment by andrenatal** [comment]
Ok

**Comment by mbebenita** [comment]
The record button has a delay (by design). The sound however plays after this delay, and it should play right when you click on it, not after.

**Comment by andrenatal** [comment]
The bip is being captured by the microphone. We should start recording only after the bip cease to send audio to the soundboard

**Comment by mbebenita** [comment]
#20 adds a shorted beep sound.
