### ISSUE TITLE
Add a gesture for the user cancel the submission while recording

### ISSUE THREAD

**Issue by andrenatal** [mozilla/voicebank-ios#7]

**Comment by mbebenita** [comment]
One idea, would be to drag the recording button down and show an X in it's place, indicating that the action is going to be cancelled.

**Comment by andrenatal** [comment]
To accomplish this will be required to either refactor LongPressRecordButton.swift to handle both LongPressGestureRecognizer and PanGestureRecognizer or add a new native UIButton and add these gestures to it.

**Comment by mbebenita** [comment]
When the finger is depressed and it's not over the button, then the recording is cancelled. While the finger is away from the button, the button should display an indication, like an "X" that it's about to get cancelled.

**Comment by andrenatal** [comment]
Ok will change the behavior to the described one.
